apiVersion: dex.coreos.com/v1
kind: OAuth2Client
metadata:
  name: kubeflow-oidc-authservice
  namespace: auth
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
id: kubeflow-oidc-authservice
secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
redirectURIs:
- /oauth2/callback
- ""
name: Dex Login Application