apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  template:
    spec:
      containers:
      - name: istio-proxy
        ports:
        - containerPort: 8080
          hostPort: 80
          protocol: TCP
        - containerPort: 8443
          hostPort: 443
          protocol: TCP
        - containerPort: 15021
          protocol: TCP
        - containerPort: 15090
          name: http-envoy-prom
          protocol: TCP
