apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.app.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes-sigs/application"
spec:
  group: app.k8s.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kubeflow
  namespace: kubeflow
spec:
  descriptor:
    type: kubeflow
    version: v2.0.0-rc.1
  componentKinds:
    - group: apps
      kind: Deployment
