apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"

resources:
- minio-deployment.yaml
- minio-pvc.yaml
- minio-service.yaml
- mlpipeline-minio-artifact-secret.yaml
