apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: https://KUBEFLOW_HOSTNAME/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: false
    staticClients:
    - idEnv: OIDC_CLIENT_ID
      redirectURIs:
      - /oauth2/callback
      - https://KUBEFLOW_HOSTNAME/oauth2/callback
      name: Dex Login Application
      secretEnv: OIDC_CLIENT_SECRET
    connectors:
    - type: oidc
      id: keycloak
      name: keycloak
      config:
        issuer: https://KEYCLOAK_DOMAIN/realms/GPUaaS
        clientID: GPUaaS
        clientSecret: $KEYCLOAK_CLIENT_SECRET
        redirectURI: https://KUBEFLOW_HOSTNAME/dex/callback
        insecureSkipVerify: true
        insecureSkipEmailVerified: true
        userNameKey: email
        scopes:
          - openid
          - profile
          - email
          - offline_access