apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../istio
- keycloak-secret.yaml

patches:
  - path: config-map.yaml
    target:
      version: v1
      kind: ConfigMap
      name: dex
      namespace: auth
  - target:
      kind: Deployment
      name: dex
      namespace: auth
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: dex
      spec:
        template:
          spec:
            containers:
            - name: dex
              envFrom:
              - secretRef:
                  name: dex-oidc-client
              - secretRef:
                  name: dex-passwords
              - secretRef:
                  name: dex-keycloak-client

